name: medical_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.10.1
dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  go_router: ^17.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/json/
    - assets/translations/
    - .env

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
